### ISSUE TITLE
cant save new keybind - forge

### ISSUE THREAD

**Issue by lmaoguy123** [Zergatul/cheatutils#100]
![image](https://github.com/user-attachments/assets/21cadcd4-af6e-4cac-b615-6825a7734657)
I even restarted minecraft and removed other mods, no success. I also tried putting other functions and change the name and i cant seem to fix it.

**Comment by Zergatul** [comment]
you are missing semicolon at the end

**Comment by lmaoguy123** [comment]
i literally just realized im so stupid sorry
