### ISSUE TITLE
BlockESP is limited to Y≃0

### ISSUE THREAD

**Issue by TheNoiselessNoise** [Zergatul/cheatutils#101]
Self-explanatory title. But some ores (below Y=0) are actually rendered.

**cheatutils-2.7.6-forge-1.20.1.jar**

![2024-09-08_00 41 31](https://github.com/user-attachments/assets/63e2223e-c6de-49ea-ad2d-65a41c1c799d)

**Comment by Zergatul** [comment]
Works fine in vanilla. I may try to fix this only if you find exact mod that causes problem. And it should be open source.

**Comment by TheNoiselessNoise** [comment]
Sorry for the false alarm. I forgot about ores in deepslate type blocks. Sometimes the most complex problems have the simplest solutions - like remembering the basic Minecraft stuff!
