### ISSUE TITLE
web GUI interface uncomfortable in mobile web browser

### ISSUE THREAD

**Issue by wibi9424** [Zergatul/cheatutils#103]
would you add more web GUI theme? so i can change whatever i like, because current theme is kinda desktop view, i need to zoom, or else, the hard thing is when editing script, sometimes the page will zoomed until the text is bigger like you just can see one word at the screen, and i cant zoom out it, i need to long press to make it trigger right click event like in pc does, then i can pinch out the pop up area, so i can zoom out the page, and sometimes your margin or padding make the text in left is out of the screen i cant move the screen to the left, but the text is in the left,

ok sorry about my language, the point is add more theme, so you can keep the current original theme in the list. make it comfortable in mobile.

because i access the localhost in mobile/my phone.

and yeah, why light level is lag, i mean minihud plugin has light level to with long range scan but no lag, but your light level is lag even just 20.

**Comment by Zergatul** [comment]
Which version are you talking about? 
Anyway, I never developed web app for mobile and I don't test it on mobile. Editing scripts from mobile seems very painful for me. Why you want to do this?
About light level. If something else works better, you can use it. You can't expect single developer to create mod which outperforms all other smaller mods.

**Comment by wibi9424** [comment]
i am using newest version 3.0.1 for minecraft 1.21.1 fabric,  as the mod said open localhost:5005,

like this gui in web browser
![Screenshot_2024-09-16-22-09-35-053_com android chrome](https://github.com/user-attachments/assets/761d25d3-6b92-4b3e-b56a-152c2b01a0f6)

or this
![Screenshot_2024-09-16-22-10-39-957_com android chrome](https://github.com/user-attachments/assets/e25652d9-2966-462b-9f44-ab0d48b95ac4)

i think you misunderstanding about "never developed web app", 

sorry i mean that interface in browser is for desktop, is not responsive web design, and i dont know where the file so i can edit the css or html, i just found the ``cheatutils.json``. so i need you to make the interface better

this is what looks like in mobile web browser
![Screenshot_2024-09-16-22-21-23-770_com android chrome](https://github.com/user-attachments/assets/8fd56fc8-dc00-474c-9c42-de1d55a55081)

this is when i try to create scripts on key bind
![Screenshot_2024-09-16-22-22-08-301_com android chrome](https://github.com/user-attachments/assets/69fd31fd-faaf-4835-9ae7-e8dfe65c60ea)

some text is on left of the screen i cant see the text, or move the screen
![Screenshot_2024-09-16-22-26-57-801_com android chrome](https://github.com/user-attachments/assets/f44555de-1b57-4dad-9c55-22950b18f0dc)


im sorry dont be angry, and im sorry if my language is not good, im still learning english language.

**Comment by wibi9424** [comment]
if you cant develop web file, let the file in the folder, so i can edit the interface whatever i want, and maybe i can upload the file so other people can use my template web design

**Comment by Zergatul** [comment]
> i think you misunderstanding about "never developed web app",

sorry, I mean I never developed web app for mobile

> if you cant develop web file, let the file in the folder, so i can edit the interface whatever i want, and maybe i can upload the file so other people can use my template web design

I can add JVM argument, so anyone can make changes to web files with compiled mod.

**Comment by Zergatul** [comment]
https://github.com/Zergatul/cheatutils?tab=readme-ov-file#debuggingcustomizing-web-app
This will be in the next version
I just don't want to release this single change just for you

**Comment by wibi9424** [comment]
> https://github.com/Zergatul/cheatutils?tab=readme-ov-file#debuggingcustomizing-web-app
> This will be in the next version
> I just don't want to release this single change just for you

yeah, its ok bro, i still can use default web interface in my laptop,

i just want to you know it, now you know it, this is one of my best mods, and just want to make it perfect,

my favourite things is, `event script`, `key binding`, and `status overlay`

**Comment by Zergatul** [comment]
Added option to use static web files from local directory in 3.1.0
