### ISSUE TITLE
Game instantly crashes when trying to render a dropped item while using Sodium 0.6.0 (Beta 2) for Fabric

### ISSUE THREAD

**Issue by LemonBomp** [Zergatul/cheatutils#104]
Tested on 2.16.2 and 3.0.1 on fabric 0.16.5. Doesn't crash on Sodium 0.6.0 (Beta 1).

**Comment by Zergatul** [comment]
sodium 0.6 has breaking change
you can disable overlay/outline for entity for now
I will release new version for 1.21 today or tomorrow

**Comment by Zergatul** [comment]
Fixed in 3.1.0

**Comment by LemonBomp** [comment]
thank you for the quick fix!
