### ISSUE TITLE
Cant use in my scribts "Main." or "events." used in many other scribts

### ISSUE THREAD

**Issue by FaZeAkir** [Zergatul/cheatutils#105]
i am using newest version 3.0.1 for minecraft 1.21.1 fabric, as the mod said open localhost:5005.

just as the title sayes i cant save my scribt if Main or events is in the code (i cant code i only copy and paste)

Error code
The name "main"
 does not exist in the current context
 
 com.zergatul.scripting.type.SUnknow@59b1b31 does not contain a definition for "event"

**Comment by Zergatul** [comment]
"main" API was in the pre-3 version of cheatutils.
In version 3+ all methods from "main" API were moved to another APIs. Just open "show API ref", Ctrl+F and find what you need

**Comment by FaZeAkir** [comment]
AH ty
