### ISSUE TITLE
[Feature Request] Slight issue with the mobs Killaura targets with possible fix.

### ISSUE THREAD

**Issue by GoliathX211** [Zergatul/cheatutils#11]
When using Killaura, vanilla mobs are targeted flawlessly and the one mob I did have a problem with is Foxhounds from Quark, the annoying hellish hound that sets you alight on attack. I can only assume that there are other cases.
One possible fix for this might be checking the entire Mob registry after instantiation (if possible) to get a list of every mob which you could then determine (as the user) which ones Killaura would be active for.

One pro of this change would allow Killaura to attack certain passive mobs that may be annoying to hit such as rabbits.

I would envision this as similar to how BlockESP works how it detects every block, including modded.

Sorry for constantly giving you more work, you always are very prompt with responses and give much appreciated insight on the mod.

**Comment by Zergatul** [comment]
Ok, I see what you mean. I will try to implement it.

**Comment by GoliathX211** [comment]
You're awesome even for taking it into mind and attempting it!

**Comment by Zergatul** [comment]
Please check 0.12.0 mod version for 1.18.2. New predefined priority entry called "Enemies" should work better with modded mobs. It will not target passive mobs like rabbits, but you can add Custom Priority Entry for any Entity class. Technically you can create Custom Priority Entry for interface (like NeutralMob or FlyingAnimal), but I didn't add UI changes for Entity ESP to display interfaces. This is only in 1.19.2 version.
