### ISSUE TITLE
schematics, how it works?

### ISSUE THREAD

**Issue by eldediamante** [Zergatul/cheatutils#117]
I don't understand how to make it work, and there is no video on youtube, could you explain it to me?

**Comment by Zergatul** [comment]
I explained how to use in matrix:
https://matrix.to/#/!IQWbOqbfcKwUjsfyRc:matrix.org/$8uTKsDp-k32luWqpD9UeEXnh5JzFYnq0OzRGshCPcoU?via=matrix.org

**Comment by eldediamante** [comment]
Thanks
