### ISSUE TITLE
Not realy an issue

### ISSUE THREAD

**Issue by MrSuperki** [Zergatul/cheatutils#13]
i accidently deleated script for free look

**Comment by Zergatul** [comment]
did you manage to create it again?

**Comment by MrSuperki** [comment]
no

**Comment by MrSuperki** [comment]
idk what to type

**Comment by Zergatul** [comment]
`freeCam.toggle();`
also you can delete `zergatul.cheatutils.json` from `config` folder in your minecraft installation, and you will start with fresh config

**Comment by MrSuperki** [comment]
thanks
