### ISSUE TITLE
option to disable the 'never forget chunk' functions in fabric

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#17]
It appears the functionality that provides the 'never forget chunk data' is intercepting the unload and preventing it from firing.  However, since this isn't a 'feature' in the fabric build, it doesn't look like I can disable it.  And, by disable, I mean not intercept the call (it's interfering with another mod that also triggers on chunk unloading).

**Comment by Zergatul** [comment]
Thank you for pointing this out. I added fix in 0.13.2, now fabric version will never skip `UnloadChunkS2CPacket`.

**Comment by end-user** [comment]
This resolved it, thanks!
