### ISSUE TITLE
conflict with lithium

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#18]
Received this (trying to update everything to 1.19.4), lithium v 0.11.1.  Not sure what the right approach would be, but it looks like lithium gets skipped.  Is it possible to have both?

[09:21:16] [Render thread/WARN]: Method overwrite conflict for getEntityManager in lithium.mixins.json:chunk.entity_class_groups.ClientWorldMixin from mod lithium, previously written by com.zergatul.cheatutils.mixins.MixinClientWorld. Skipping method.

**Comment by end-user** [comment]
Of course, I see that I'm using cheatutils for v1.19.3 so that might be an issue too

**Comment by Zergatul** [comment]
Does it cause any problems? If methods in both mods have the same body (from its name I assume it should be the same), then we should be fine. You have link to Lithium source?

**Comment by end-user** [comment]
https://github.com/CaffeineMC/lithium-fabric

**Comment by Zergatul** [comment]
Methods have the same body, it should work fine. One of mods should use another name to remove this warning.

https://github.com/CaffeineMC/lithium-fabric/blob/069a0af86ec299a7bb39fe3a2539a8bbdd2b3933/src/main/java/me/jellysquid/mods/lithium/mixin/chunk/entity_class_groups/ClientWorldMixin.java#L18
https://github.com/Zergatul/cheatutils/blob/1.19.3-fabric/src/main/java/com/zergatul/cheatutils/mixins/MixinClientWorld.java#L18

**Comment by end-user** [comment]
Well, looks like I'm also awaiting a version for 1.19.4

**Comment by end-user** [comment]
is 1.19.4 for fabric in the works?

**Comment by Zergatul** [comment]
> is 1.19.4 for fabric in the works?

It is actually ready, but I got stupid bug which is pretty hard to debug. First time you start minecraft with mod - cheatutils hotkeys don't work. You have to change at least one cheatutils hotkey and it fixes the issue. I didn't want to release 1.19.4 fabric just because of this bug.

**Comment by end-user** [comment]
understood - just checking.

**Comment by Zergatul** [comment]
added 1.19.4 ver

**Comment by end-user** [comment]
Looks like it's working.  Still gives the method conflict warning, but seems ok.
