### ISSUE TITLE
Fabric crash 1.19.2

### ISSUE THREAD

**Issue by TaysMelons** [Zergatul/cheatutils#23]
shouldersurfing->@Redirect::doRenderCrosshair(Lnet/minecraft/class_5498;)Z with priority 1000, already redirected by zergatul.cheatutils.mixins.json:common.MixinGui from mod cheatutils->@Redirect::onRenderCrosshairIsFirstPerson(Lnet/minecraft/class_5498;)Z with priority 1000

[19:13:56] [main/ERROR]: [net.fabricmc.loader.impl.launch.FabricLauncherBase#handleFormattedException] Minecraft has crashed!

Pastebin :
https://pastebin.com/gXt7R16R

**Comment by Zergatul** [comment]
It's a conflict with some other mod.

**Comment by Zergatul** [comment]
Could you join mod discord and test jar I will try to build with fix for that?

**Comment by TaysMelons** [comment]
Sure could you relink the discord plz?
