### ISSUE TITLE
[2.4.0, 1.19.4] Max chat history mixin error - TweakerMore incompatibility

### ISSUE THREAD

**Issue by tajemniktv** [Zergatul/cheatutils#25]
Hey, after updating to 2.4.0 it's spitting out error about failing to inject `onModifyMaxChatHistory`. 
I'm not really good at reading logs but I'm hoping that these might help figuring out what's going on: https://mclo.gs/aYX2IOk
I'm guessing it's some kind of mod-feature conflict. 

Cheers!

**Comment by Zergatul** [comment]
It is conflicting with `nochatreports` mod. If you can play without it, try removing it

**Comment by tajemniktv** [comment]
https://mclo.gs/VJw9CNL

Hey, thanks for the info. Disabling it didn't work, although it allowed me to see that `tweakermore-mc1.19.4-v3.12.0.jar` is responsible for the incompat. I will try tweaking TweakerMore config to disable some of it's functions and see if it works. 
All of these mods seem to work fine along CheatUtils 2.4.0:
![image](https://github.com/Zergatul/cheatutils/assets/12156943/3f131f26-39d9-4468-be88-f10195733243)
I hope this info helps!

**Comment by Zergatul** [comment]
Yes... it looks like tweakermore trying to increase chat limit as well. Disabling functions will not help, since mixins work before minecraft classes are loaded into memory.
The only thing I can do is to mark some (or all?) mixins as not required, preventing crash. In this case some modules may not work as expected.

**Comment by tajemniktv** [comment]
If that would only "break" chat related modules then I don't mind that much. I just hope that won't create a wave of issues because "something isn't working" because of an incompatibility... 
I appreciate your work and help in both creating the mod and resolving this issue!

**Comment by Zergatul** [comment]
I will not resolve this soon. I have to carefully check mixins one by one and mark some of them as non-required.
If you can build mod by yourself you can try edit `zergatul.cheatutils.mixins.json` file and set `defaultRequire` to `0`.

**Comment by tajemniktv** [comment]
That is no problem at all,
I would like to just say that I'm really grateful for how you are handling this issue and that I really appreciate your instructions!:)

**Comment by tajemniktv** [comment]
Fallen Breath is trying to fix it on TweakerMore side: https://github.com/Fallen-Breath/tweakermore/commit/c68fda30b163f62d16c3f1c961a337983624e2d0
I'm not closing it yet as dev might want to keep this issue still open (or not, if so you can simply close it for me lol)
Cheers and thanks again for the help!<3

**Comment by Zergatul** [comment]
Ok. These conflicts are always annoying to fix.

**Comment by Zergatul** [comment]
In 2.4.2 version I made all mixins non-required. Game shouldn't crash at start.

**Comment by tajemniktv** [comment]
Hey, I can confirm that it's both fixed on TweakerMore side and on CheatUtils side!:) 
Thanks
