### ISSUE TITLE
[2.4.1, 1.19.4] Mixin transformation of net.minecraft.client.render.WorldRenderer failed

### ISSUE THREAD

**Issue by tajemniktv** [Zergatul/cheatutils#27]
Hey, after updating to 2.4.1 it crashes and spitting out some issues about world render, sodium. Downgrading to 2.4.0 does in fact help. 

## Environment

- Minecraft version: '1.19.4'
- Mod version: 'CheatUtils 2.4.1'
- Java:  v20.0.1, amd64 architecture, Eclipse Adoptium.
- Java Arguments: `[-XX:+UseG1GC, -XX:+ParallelRefProcEnabled, -XX:MaxGCPauseMillis=200, -XX:+UnlockExperimentalVMOptions, -XX:+UnlockDiagnosticVMOptions, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -XX:G1NewSizePercent=30, -XX:G1MaxNewSizePercent=40, -XX:G1HeapRegionSize=8M, -XX:G1ReservePercent=20, -XX:G1HeapWastePercent=5, -XX:G1MixedGCCountTarget=4, -XX:InitiatingHeapOccupancyPercent=15, -XX:G1MixedGCLiveThresholdPercent=90, -XX:G1RSetUpdatingPauseTimePercent=5, -XX:SurvivorRatio=32, -XX:+PerfDisableSharedMem, -XX:MaxTenuringThreshold=1, -XX:UseAVX=3, -XX:+UseStringDeduplication, -XX:+UseFastUnorderedTimeStamps, -XX:+UseAES, -XX:+UseAESIntrinsics, -XX:UseSSE=4, -XX:+UseFMA, -XX:AllocatePrefetchStyle=1, -XX:+UseLoopPredicate, -XX:+RangeCheckElimination, -XX:+EliminateLocks, -XX:+DoEscapeAnalysis, -XX:+UseCodeCacheFlushing, -XX:+SegmentedCodeCache, -XX:+UseFastJNIAccessors, -XX:+OptimizeStringConcat, -XX:+UseCompressedOops, -XX:+UseThreadPriorities, -XX:+OmitStackTraceInFastThrow, -XX:+TrustFinalNonStaticFields, -XX:ThreadPriorityPolicy=1, -XX:+UseInlineCaches, -XX:+RewriteBytecodes, -XX:+RewriteFrequentPairs, -XX:+UseNUMA, -XX:-DontCompileHugeMethods, -XX:+UseFPUForSpilling, -XX:+UseFastStosb, -XX:+UseNewLongLShift, -XX:+UseVectorCmov, -XX:+UseXMMForArrayCopy, -XX:+UseXmmI2D, -XX:+UseXmmI2F, -XX:+UseXmmLoadAndClearUpper, -XX:+UseXmmRegToRegMoveAll, -Dfile.encoding=UTF-8, -Xlog:async, -Djava.security.egd=file:/dev/urandom, --add-modules, jdk.incubator.vector, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6144m, -Duser.language=en]`

## Log: 

https://mclo.gs/f26VkXz

Likely most relevant log:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/WorldRenderer::onRenderChunkLayer with priority 1000 cannot inject into net/minecraft/WorldRenderer::renderLayer(Lnet/minecraft/RenderLayer;Lnet/minecraft/MatrixStack;DDDLorg/joml/Matrix4f;)V merged by me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> #cheatutils:zergatul.cheatutils.mixins.json:common.MixinLevelRenderer from mod cheatutils -> Prepare Injections ->  -> handler$kpb000$cheatutils$onRenderChunkLayer(Lnet/minecraft/RenderLayer;Lnet/minecraft/MatrixStack;DDDLorg/joml/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]`

**Comment by Zergatul** [comment]
In 2.4.2 version I made all mixins non-required. Game shouldn't crash at start.

**Comment by tajemniktv** [comment]
Hey, can confirm that the game does not crash on start!:)
Thanks
