### ISSUE TITLE
Error: package ___ does not exist (1.19.2)

### ISSUE THREAD

**Issue by CodeByAidan** [Zergatul/cheatutils#28]
Hi! So I was trying to look at the source code and tinker a few things, so I opened up Intellij IDEA, and ran the simple `gradlew build` task. It seems as if the symlinks didn't work? I did use:

```sh
git config --global core.symlinks true
```

to no avail... :(

Here is the Gradle Scan build logs: [https://scans.gradle.com/s/krbbsqijiuneq](https://scans.gradle.com/s/krbbsqijiuneq)

Gradle 7.6, Eclipse Temurin OpenJDK Runtime Environment 18.0.2.1+1

https://github.com/Zergatul/cheatutils/assets/67598470/d331f51d-9b00-47a0-8b67-3a44c6eb0667

**Comment by Zergatul** [comment]
You did something wrong, symlinks weren't created. On your video `accessors`, `chunkoverlay`, `collections` and so on are files, but they should be directory symlinks.
When you ran `git clone` did it have enough permissions to create symlink?

**Comment by CodeByAidan** [comment]
I gave it everything, re-installed git, did global and local configurations, I got it close once, but I eventually gave up. I just manually moved it and it's fine now, only other issue is that the localhost:5005 server is not running after my build?

[https://scans.gradle.com/s/avvbfnx6vlbv6](https://scans.gradle.com/s/avvbfnx6vlbv6)

https://github.com/Zergatul/cheatutils/assets/67598470/340c79c8-1424-4b4e-ab61-f8e05185922a

**Comment by Zergatul** [comment]
Server is working, you are getting 404 HTTP error.
Maybe you didn't move resources directory with html/javascript files.

**Comment by CodeByAidan** [comment]
Thank you it worked!
