### ISSUE TITLE
Mod most of the time does not allow for other players to be hit and screen jetters when attacking a player - Fabric 1.20.1

### ISSUE THREAD

**Issue by Dormant11** [Zergatul/cheatutils#29]
When attacking a player most of the time the player will not get hit and if you hold the attack the screen jitter and disconnects you for invalid packets (Fabric 1.20.1.

**Comment by Zergatul** [comment]
You are asking about Kill Aura?
1. What range you specified? If you entered large value then server will ignore attack attempts.
2. Why you hold attack while Kill Aura is active?

**Comment by Dormant11** [comment]
The problem is still there when I turn off all the hacks and the range is around 2 blocks

**Comment by Zergatul** [comment]
How fast you configured kill aura to attack?

**Comment by Dormant11** [comment]
Even when I have it off it happens, I deleted the mod and re downloaded and nothing changed.

**Comment by Zergatul** [comment]
Servers may have anti cheat for different type of kill auras.
I asked you above, how quickly your kill aura attacks?
How do you know players are not getting hit?

**Comment by Dormant11** [comment]
My kill aura's speed is attack cooldown (the problem is still there when I have all the hacks turned off). This happens in all the servers and I know the player is not getting hit because they don't take damage, there is no sound, and there is no knock back. I tested this with a friend and they screen shared, there was no damage taken.

**Comment by Zergatul** [comment]
Very strange. I am not pvp guy, and I never really used my kill aura on players. I will check later with 2 accounts.

**Comment by Zergatul** [comment]
I just checked this on fabric 1.20.1, with latest cheatutils.
It works fine. It hits another player.
How did you make Kill Aura attack players? You added predefined priority entry, or created custom by specifying class name?

**Comment by Dormant11** [comment]
My priority is Enemies (off), Shulker Bullets (on), Fireballs (on), Players (off). I have no specifying class name for the player.

**Comment by Zergatul** [comment]
Ok, maybe you messed up in Hitbox Size module? F3+B you can check active hitboxes.
If you delete/redownload mod you actually doesn't change anything. All settings are stored in config folder,  in `zergatulcheatutils.json` file. If you really want to reset settings, delete this file and restart game

I tested by myself, I can hit other players normally

**Comment by Dormant11** [comment]
Thank you, it worked out.

**Comment by Dormant11** [comment]
Strange, sometimes the lever does not switch when I click.

**Comment by Zergatul** [comment]
I don't think this can be related to my mod

**Comment by Dormant11** [comment]
Yes you are right, this matter is dealt with. Thank you!
