### ISSUE TITLE
mod conflict (plus crash)

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#30]
It appears it's conflicting with Baritone (on fabric 1.20.1) and crashing.  I'm seeing this warning

`@Redirect conflict. Skipping mixins.baritone.json:MixinMinecraft from mod baritone->@Redirect::passEvents(Lnet/minecraft/class_310;)Lnet/minecraft/class_437; with priority 1000, already redirected by zergatul.cheatutils.mixins.json:common.MixinMinecraft from mod cheatutils->@Redirect::onTickScreenPassEvents(Lnet/minecraft/class_310;)Lnet/minecraft/class_437; with priority 2000`

**Comment by Zergatul** [comment]
Please check 2.7.0 version. I verified it doesn't crash with baritone

**Comment by end-user** [comment]
Works great!  Thanks for being so responsive!
