### ISSUE TITLE
ExcellentEnchants

### ISSUE THREAD

**Issue by EmptyDagon** [Zergatul/cheatutils#34]
Is there any way to use enchantments from ExcellentEnchants plugin in VillagerRoller? As I understand, it is not possible to identify additional enchantments from this plugin either by id or by name.

**Comment by Zergatul** [comment]
How do you know it is not possible?

**Comment by EmptyDagon** [comment]
> How do you know it is not possible?

I'm sorry, I guess the translator didn't translate the meaning of my words correctly. I meant that I think so, because the api commands to show the name and id didn't work correctly (showed vanilla enchantments, but not additional ones).

**Comment by EmptyDagon** [comment]
I accidentally closed the comments.....

**Comment by Zergatul** [comment]
So what you see in the log if you log enchantment names/ids in the system chat?

**Comment by EmptyDagon** [comment]
The work of this plugin is that it adds additional enchantments to the existing ones, so it shows only all vanilla (example: a book with the enchantment "mending" falls out, and to it in white color in the description attributed to more enchantments).

[25aug.2023 12:33:20.064] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] [Roller] minecraft:binding_curse Curse of binding 1 @ 28 --- 280%
[25aug.2023 12:33:21.563] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] [Roller] minecraft:channeling Channeling 1 @ 8 --- 160%

**Comment by Zergatul** [comment]
That's strange way to implement custom enchantments. Villager Roller module only see what's possible in vanilla minecraft code. I mean you can add new enchantment with new id and name, and module should be able to work with. But your mod seems like use something another.

**Comment by EmptyDagon** [comment]
Does that mean there is no way to use Villager Roller with this plugin? And is there any way to see multiple enchantments at one book at once?

**Comment by Zergatul** [comment]
At current state - no. Villagers only propose single enchantment in vanilla, right?

**Comment by EmptyDagon** [comment]
Yes, that's correct. Too bad, I really wanted to use your great tool with this plugin

**Comment by EmptyDagon** [comment]
Should I close this thread?

**Comment by Zergatul** [comment]
Yes, you can close it
