### ISSUE TITLE
ESP Broken

### ISSUE THREAD

**Issue by Aetrnl94** [Zergatul/cheatutils#35]
Hi, this mod is a life-saver. I recently made a ton of changes to my save and for some reason the CheatUtils are a bit broken; the in-game controls from setting custom scripts just are generic ('reserved 00'; 'reserved 01' instead of what I named them) and my list of blocks I had added to the ESP vision setting is blank and I cannot add new ones (typing in 'minecraft:chest', 'chest', or anything really just shows a blank list). I tried deleting the zergatulcheatutils.json, deleting the mod, then reinstalled it but it didn't fix the issue.

Thanks!

**Comment by Zergatul** [comment]
Maybe you installed some new mod and it caused problems?

**Comment by Aetrnl94** [comment]
It's definitely possible, but I'm running over 350 mods so it's hard to say. Can you think of any mods (or categories) that would cause the block-list do disappear? Or is there a maximum number of entities that it'll show (because several mods add a lot of new blocks)?
Thanks!

**Comment by Zergatul** [comment]
There is no limits on how much entities or blocks can be displayed.
What do you see when you try to open these URLs:
- http://localhost:5005/api/block-info
- http://localhost:5005/api/entity-info

**Comment by Aetrnl94** [comment]
When I go to http://localhost:5005/api/entity-info:
![image](https://github.com/Zergatul/cheatutils/assets/131720204/979ed78e-03ab-42d2-8dcc-de4b108b4059)
When i go to http://localhost:5005/api/block-info:
![image](https://github.com/Zergatul/cheatutils/assets/131720204/bb5e63ec-7e7c-4303-8bef-d0028d3db448)

**Comment by Zergatul** [comment]
Can you pinpoint exact mod that causes block-info to return error?
