### ISSUE TITLE
mod conflict with sodium

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#37]
I _think_ this is a conflict with sodium?

`Mixin apply for mod cheatutils failed zergatul.cheatutils.mixins.json:common.MixinLevelRenderer from mod cheatutils -> net.minecraft.class_761: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_761::onRenderChunkLayer with priority 500 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLorg/joml/Matrix4f;)V merged by me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin with priority 1000 [ -> handler$zle000$cheatutils$onRenderChunkLayer(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLorg/joml/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_761::onRenderChunkLayer with priority 500 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLorg/joml/Matrix4f;)V merged by me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin with priority 1000 [ -> handler$zle000$cheatutils$onRenderChunkLayer(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLorg/joml/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]`

**Comment by Zergatul** [comment]
What is game version?

**Comment by end-user** [comment]
sorry; mc v1.20.1 w/ sodium 0.5.2.  I think it was working with the previous cheatutils.

**Comment by end-user** [comment]
Actually, it may be working, but there's still an error in the log

**Comment by Zergatul** [comment]
Some time ago I added option to "silently continue" if mixin error occurs in cheatutils. That means there is conflict, and something may not work, but at least it is not crashing.

**Comment by end-user** [comment]
Ok, well I _think_ one thing that's not working is the pearl path.  Can test with the other traces too, but I assume those won't work either.  FWIW, it _was_ but that might have been before upgrading to 1.20.

**Comment by Zergatul** [comment]
This particular mixin from your error is necessary only for Schematica module.

**Comment by end-user** [comment]
still seeing it in the log, but closing as the mod is working.
