### ISSUE TITLE
Crash on teleport command

### ISSUE THREAD

**Issue by DangerStep** [Zergatul/cheatutils#38]
If you input an invalid value (mine crashed when I put "500\\") as the first argument for "teleport.toCrosshair", it crashes the game. nothing game breaking, just wanted to let you know.

**Comment by Zergatul** [comment]
This shouldn't happen, thanks, I will check

**Comment by Zergatul** [comment]
How does exactly your script looks like? Game crashes on script save, or when you execute it by using assigned key?

**Comment by DangerStep** [comment]
I'm using the execute feature to teleport

**Comment by Zergatul** [comment]
Just give me exact text which causes crash

**Comment by DangerStep** [comment]
It's ".teleport.toCrosshair(500/, 20);"

**Comment by DangerStep** [comment]
.teleport.toCrosshair(20, 500\);

**Comment by Zergatul** [comment]
It shows error in chat for me... Checked forge 1.20.1

**Comment by Djspac3** [comment]
well, that's odd for sure the compiling I would think would notice the error so I think it would be the compiler that's crashing oddly
