### ISSUE TITLE
1.18.2 mob search

### ISSUE THREAD

**Issue by TaysMelons** [Zergatul/cheatutils#4]
When using block scanning I can search modded blocks other then eg minecraft:bee

When scanning entitys it only shows minecraft mobs only

Could you add searching for modded entitys
Eg. Productivebees:ender_bee

For 1.18.2 forge

**Comment by Zergatul** [comment]
This was my original idea, but I didn't find a way how to implement it (I am new to Java). So I hardcoded static list of entity types. I will check again what I can do.

**Comment by Zergatul** [comment]
I added new 1.18.2 and 1.19.2 version. I didn't test it with mod with custom entities. Let me know if it works
