### ISSUE TITLE
status overlay not working

### ISSUE THREAD

**Issue by guy39657** [Zergatul/cheatutils#40]
ive tried disabling every other mod in my modpack and it still wont work.
i cant mess around with mod configuration.
i can only guess its a problem witht the mod itself.
here's my code so far (i hope you like pasta):

if (main.isDebugScreenEnabled()) {
    main.setOverlayHorizontalPosition("center");
    main.setOverlayVerticalPosition("top");
    main.addText("#FFFFFF","Debug");
} else {
main.setOverlayHorizontalPosition("right");
main.setOverlayVerticalPosition("top");
main.addText("localhost:5005");
    if (shulkerTooltip.isEnabled()) {
        main.addText("#FFFFFF","Shulker Tooltip (Right Alt)");
    } else {
        main.addText("#555555","Shulker Tooltip (Right Alt)");
    }
    if (scaffold.isEnabled()) {
        main.addText("#55FF55","Scaffold (`)");
    } else {
        main.addText("#FF5555","Scaffold (`)");
    }
    if (noFall.isEnabled()) {
        main.addText("#55FF55","Fallsafe (B)");
    } else {
        main.addText("#FF5555","Fallsafe (B)");
    }
    if (flyHack.isEnabled()) {
        main.addText("#55FF55","Flight (V)");
    } else {
        main.addText("#FF5555","Flight (V)");
    }
    if (freeCam.isEnabled()) {
        main.addText("#55FF55","Freecam (F5)");
    } else {
        main.addText("#FF5555","Freecam (F5)");
    }
}

**Comment by guy39657** [comment]
woops a mistake has been made in the above code example

if (main.isDebugScreenEnabled()) {
    main.setOverlayHorizontalPosition("center");
    main.setOverlayVerticalPosition("top");
    main.addText("#FFFFFF","Debug");
} else {
main.setOverlayHorizontalPosition("right");
main.setOverlayVerticalPosition("top");
main.addText("localhost:5005");
    if (shulkerTooltip.isEnabled()) {
        main.addText("#FFFFFF","Shulker Tooltip (Right Alt)");
    } else {
        main.addText("#555555","Shulker Tooltip (Right Alt)");
    }
    if (scaffold.isEnabled()) {
        main.addText("#55FF55","Scaffold (CHARACTER TILDE NOT ACTUAL BUT IT BROKE IT)");
    } else {
        main.addText("#FF5555","Scaffold (SAME AS ABOVE LOL)");
    }
    if (noFall.isEnabled()) {
        main.addText("#55FF55","Fallsafe (B)");
    } else {
        main.addText("#FF5555","Fallsafe (B)");
    }
    if (flyHack.isEnabled()) {
        main.addText("#55FF55","Flight (V)");
    } else {
        main.addText("#FF5555","Flight (V)");
    }
    if (freeCam.isEnabled()) {
        main.addText("#55FF55","Freecam (F5)");
    } else {
        main.addText("#FF5555","Freecam (F5)");
    }
}

**Comment by Zergatul** [comment]
What do you mean it doesn't work? Nothing is displayed? Then why you wrote such long script? If it doesn't work you should start with something basic.
Did you enable checkbox on Status Overlay page?
