### ISSUE TITLE
Sodium conflicting with block ESP rendering

### ISSUE THREAD

**Issue by Dormant11** [Zergatul/cheatutils#41]
ESP for blocks does not work with sodium.

**Comment by Zergatul** [comment]
I have no idea what sodium does, but in forge world ESP rendering doesn't work with custom shaders (like with optifine). It still works with optifine if you don't use fancy shaders.

**Comment by end-user** [comment]
@Dormant11 Please try again with 2.7.3 - it's working for me.

**Comment by Zergatul** [comment]
Fixed in 2.7.3
