### ISSUE TITLE
Render distanze bug with Rubidium

### ISSUE THREAD

**Issue by Quantum-mutnauQ** [Zergatul/cheatutils#42]
I made my an FPS mod pack included Rubidium. Then I load them with cheat utils by using forge. When I join an forge server and my render distance set to 32(server too), cheat utils brake the render distance down to 1 chunk and 10 blocks high. Entity and particles render normal. Only blocks doesn't render. 
With cheat utils:
![2023-09-25_17 53 04](https://github.com/Zergatul/cheatutils/assets/141065355/43c3ccf2-2bed-46f7-b105-18d0c8c2d68a)
With out:
![2023-09-25_17 54 51](https://github.com/Zergatul/cheatutils/assets/141065355/e8e98c3a-9c66-43bb-b1c0-527a9afe8c80)

Download Rubidium: https://www.curseforge.com/minecraft/mc-mods/rubidium

Forge 1.20.1 - 47.2.0
Do you have any idea how i can fix it?
Thank you for your help;
Quantum_mutnauQ

**Comment by Zergatul** [comment]
You will definitely have to make code changes to fix this. Other guys reported similar issue in the past, but I don't pay much attention to mod conflicts problems. Maybe it is related to "Chunks" module code which is under visuals. 
I may look into this later.

**Comment by Quantum-mutnauQ** [comment]
thanks,
It woud be nice if you look into it.

**Comment by Zergatul** [comment]
I reproduced this issue. It is caused by Fog module. I have it enabled with **Skip FogRenderer.setupFog(...)** option.
And there is note on this page:
> First option may not work properly with graphic optimization mods or shaders. 

Please read carefully next time. I can't remember all these things.

**Comment by Quantum-mutnauQ** [comment]
Many thanks,
I will try this I hope tis will worke because I switch form Rubidium to Embeddium. I think it will worke because Embeddium and Rubidium are basically the same.

Sorry, I have overlooked this.
