### ISSUE TITLE
1.20.2 issue?

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#43]
I don't know if this is a 1.20.2 issue, but I get an error during load, and when I try to join a server, I get this and it doesn't connect.

Client disconnected with reason: Internal Exception: java.lang.NoSuchMethodError: 'net.minecraft.class_1934 net.minecraft.class_2678.comp_90()'

**Comment by Zergatul** [comment]
1.20.2 requires few code changes, you can't use 1.20.1 version. I will update in few days

**Comment by Zergatul** [comment]
Added 1.20.2 version

**Comment by end-user** [comment]
yep, works.
