### ISSUE TITLE
Block/Entity Tracer Lines not showing 

### ISSUE THREAD

**Issue by TaysMelons** [Zergatul/cheatutils#49]
when enabled only an outline of the block/entity is displayed, no line tracer.
- Tracer option is enabled
- Outline is enabled
latest forge version of the mod for 1.20.1

let me know what info to attatch.

**Comment by Zergatul** [comment]
Can be conflict with another mod, or simply custom shaders loaded by mods like optifine can break these lines

**Comment by Zergatul** [comment]
This should be fixed in 2.7.3 version
