### ISSUE TITLE
Please could you backport minimap update to 1.18.2

### ISSUE THREAD

**Issue by TaysMelons** [Zergatul/cheatutils#5]
Hi could you please port the update to 1. 18.2 
'added chunk rendering features'

Specifically the minimap ExplorationMiniMapController.java :
unloadChunk(ChunkAccess chunk) >
 unloadChunk(Dimension dimension, ChunkAccess)

Cauing game crashes other modded packs with external dimensions, works with "overworld" but other dimensions it crashes

I tried to fix it myself but failed to compile
Thank you in advance

**Comment by Zergatul** [comment]
Hi, ok, I will look into it. It was pretty massive change in 1.19 version, no wonder it is hard to you to fix. BTW do you have some public server where I can test custom dimension?

**Comment by Zergatul** [comment]
Fixed in 0.8.1 version for 1.18.2
