### ISSUE TITLE
forge 1.20.1 mods, server cant load chuncks

### ISSUE THREAD

**Issue by mrKayan-code** [Zergatul/cheatutils#50]
when i relog to server i load chunck, when i go to new territory its not chunks
![javaw_3mUWgI0OWi](https://github.com/Zergatul/cheatutils/assets/83054035/9f32f96c-5193-4d31-b017-bd1e3b37e4e7)

**Comment by Zergatul** [comment]
Do you have no fog enabled?

**Comment by mrKayan-code** [comment]
hi, i fixed this bug(thanks [Fran12334](https://github.com/Fran12334)) he writed issue same with my, it was, because my render distance was below, than server render distance, i needed just to max my render distance

**Comment by mrKayan-code** [comment]
link to [Quilt 1.19.4 cheatutils 2.4.0] not rendering chunks outside of initial view distance
#26
