### ISSUE TITLE
Area Mine scripting 

### ISSUE THREAD

**Issue by Gith263** [Zergatul/cheatutils#52]
Ok I may lack the intelligence on this one.  But I am trying to use the area mine feature.  Now on the are mine feature it says "Automatically mines blocks surrounding your target block. Activates only when instamine is active."  No worries decently straight forward.  So I look for the instamine feature and cannot find it.  I went to the Show/Hide API Reference and did not see anything on there about mining.  So i think to myself not one the API reference card no big problem, so I type out  "instamine.toggle();"  and I get the error code "Cannot find field "instamine".".  a little grumpy that this did not work I of course tried "areamine.toggle();" for the slightly different result of "Cannot find field "areamine".", So please tell me how I can toggle this on and off

**Comment by Zergatul** [comment]
API Reference is generated automatically, it simply shows everything. Not every checkbox/input value has corresponding API methods. Originally I didn't want to overwhelm API with tons of methods. I will add methods for instamine in the next version.

**Comment by Gith263** [comment]
Thank you,  So currently the area mine/ Instamine does not have a API method in it correct?  I am asking to make make sure that I have it right.  Sorry for being a pain about it.  

Also thank you for your quick response

**Comment by Zergatul** [comment]
Correct

**Comment by Gith263** [comment]
Thank you,  I will look forward to the update when you can work it in.  :)
