### ISSUE TITLE
Sodium breaks gui/esp

### ISSUE THREAD

**Issue by normalUserKarn** [Zergatul/cheatutils#58]
when i use sodium all tracers and overlay dissapear

**Comment by Zergatul** [comment]
This is fixed in 2.7.3, but this is only in MC 1.20 versions. I don't have time to support other versions

**Comment by normalUserKarn** [comment]
is there any way i could fix it myself?

**Comment by Zergatul** [comment]
If you know Java, and can build mod by yourself - yes
