### ISSUE TITLE
Could you please backport some features to forge 1.18.2

### ISSUE THREAD

**Issue by Wiz75-GitHub** [Zergatul/cheatutils#6]
Love this mod and wanted to thank you for all you have done!!!

I have a request and I'm not sure if this is the right place to ask for this, if not please feel free to delete my request.

Would you be able to port some of the 1.19.2 forge features to 1.18.2 forge?
As much as I would love to updating to 1.19.2 is not possible.

Here is the list of feature I'm interested in.

=== Automation ===
Auto Drop
Container Buttons
Auto Eat

=== Hacks ===
Movement Hack
	- No slow on crouch
	- Anti-Knockback
	- Anti-Push
Scaffold
	- Attach to air
No Fall

=== Visuals ===
Fog
Particles

Thanks in advance!!!
Wiz75

**Comment by Zergatul** [comment]
Hi, that's ok to put requests here. I don't have much time this week, I will try add these modules in few days.
Glad to see someone uses Auto Drop and Container Buttons.

**Comment by Zergatul** [comment]
Added in 0.9.0 forge version
