### ISSUE TITLE
[Feature Request] chat messages when blocks found

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#61]
It would be nice to have a chat message pop up when specified block types are found (because, while block finder may highlight them, the player may not see them right away).  It would need to be per-block type, and you could use the block highlight color in the chat message.  There would need to be a cool-down on the message function so chat isn't spammed if multiple blocks of the same type load together (20 chests all at once, for example).

**Comment by Zergatul** [comment]
I had an idea to implement something like `blocks.count("minecraft:chest")`, and users can do whatever they want with this information. Display on the screen, or send in chat. Cooldown will have to be implemented manually.

**Comment by end-user** [comment]
I think I'd need to see an example of how to use that.

**Comment by Zergatul** [comment]
Ok, I will show example. I am currently working on block groups, made some good progress.

**Comment by Zergatul** [comment]
Do you use fabric?

**Comment by end-user** [comment]
Yep.

**Comment by Zergatul** [comment]
Uploaded few fabric version for 1.20.2
Example script for your scenario: https://github.com/Zergatul/cheatutils/wiki/Script-Examples#show-message-in-chat-when-block-esp-sees-new-blocks-in-render-distance
