### ISSUE TITLE
Exploration Mini Map does not turn off

### ISSUE THREAD

**Issue by AlpJust** [Zergatul/cheatutils#66]
I ran into the following problem: the "Exploration Mini Map" does not turn off. There is no line responsible for this in the references, even the complete deletion of the .minecraft folder did not give a result. After installing a clean build and this mod on it, the minimap still appears. How do I turn it off completely? It just destroys my fps.

A little extra information:
Game version 1.20.1
Mod version: zergatul.cheatutils-2.7.3-forge-1.20.1

Ну и на сколько я понял ты русскоговорящий, так что вот исходный текст не пропущенный через транслейтор:
Я столкнулся со следующей проблемой: не выключается "Exploration Mini Map". Нет строки отвечающей за это в референсах, даже полное удаление папки .minecraft не дало результата. После установки чистой сборки и этого мода на неё, миникарта всё ещё появляется. Как мне полностью отключить её? Она просто уничтожает мой фпс.

Немного экстра инфы: 
Версия игры 1.20.1
Версия мода: zergatul.cheatutils-2.7.3-forge-1.20.1
![javaw_R30OUgqz84](https://github.com/Zergatul/cheatutils/assets/74210310/2ccd50ba-2d12-4136-964d-1d24fc6a2e78)

**Comment by Zergatul** [comment]
This is not my minimap. This is some another mod.

**Comment by AlpJust** [comment]
> This is not my minimap. This is some another mod.

Yes, I just realized it myself and was about to close/delete the post, but you already answered, so I'm sorry. It was a strange coincidence, because this minimap appeared after activating that very function, and I forgot about the existence of this mod in the mod pack.
