### ISSUE TITLE
[Enhancement] add glow conditional on entity properties

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#67]
Maybe this is possible through scripting and I don't know how to go about it.  What would be nice is to be able to add entity glow conditionally based on entity properties.  A big one is highlighting drowned carrying tridents, but could also include mobs with one or more diamond armor, or horses with a speed of 14+.  Things like that.

**Comment by Zergatul** [comment]
For drowned I just enable "Show Equipped Items" and I can see drowned with trident easily. Same with diamond armor.
It is not the same effect as having script to decide which entity to highlight, but decent workaround.

As for adding script conditions for blocks/entities ESP. I was thinking about this, but it will be big amount of work.

**Comment by Zergatul** [comment]
Will add this in the next version. Example:
```c#
int id = currentEntityEsp.getId();
float speed = game.entities.getHorseMovementSpeed(id);
float jump = game.entities.getHorseJumpHeight(id);
currentEntityEsp.setTitle(
    "Speed: " + convert.toString(speed, 3) + 
    " / Jump: " + convert.toString(jump, 2));
```

Available methods:
```c#
currentEntityEsp.disableCollisionBox()
currentEntityEsp.disableOutline()
currentEntityEsp.disableOverlay()
currentEntityEsp.disableTracer()
currentEntityEsp.getId() → int
currentEntityEsp.setTitle(string title)
```

![image](https://github.com/Zergatul/cheatutils/assets/1272144/6e01ba9c-cff2-4353-8682-f08ca26f40b1)

**Comment by Zergatul** [comment]
Added in 2.13.0
