### ISSUE TITLE
Block ESP not showing

### ISSUE THREAD

**Issue by asdat3** [Zergatul/cheatutils#69]
I am unsure of the reason, Entity ESP aswell as all other functions work flawless but Block ESP doesnt show any blocks.
Checked the ids with F3 no idea what I am doing wrong

using 19.2

let me know what you need from me

**Comment by Zergatul** [comment]
Block ESP works very different to Entity ESP.
When you on F3 debug screen, check what BlockFinder Thread status is (left-bottom). It should has zero items in queue, and has some number of chunks loaded.
Do you use some big modpack?

**Comment by asdat3** [comment]
BlockFinder Scam: queue size=0; load=0.03%; Thread State=Waiting (queue size=1, every few seconds for a few ms)
.. queue size=0; State=Waiting
.. queue size=0; State=Waiting

loaded chunks: 0

I am using the Steampunk modpack (302 mods)

**Comment by Zergatul** [comment]
> loaded chunks: 0

This is not good. Some mod probably cause this problem. Sorry, I don't support 19.2 anymore, and this issue will probably take a lot of time to fix.

**Comment by asdat3** [comment]
anything I can try? (except disabling mods)

**Comment by Zergatul** [comment]
No, this is problem in the code

**Comment by asdat3** [comment]
hm okay thanks anyways for the quick reply
