### ISSUE TITLE
Web menu, block esp list broken

### ISSUE THREAD

**Issue by HitoshiMossi** [Zergatul/cheatutils#71]
for some reason web menu doesnt show list of blocks that i enabled in "Blocks", also when i press "Add block" the "Back" button wont work but if i reload the page or re-open it, it will bring me back to "main menu" if you can say so.

**Comment by HitoshiMossi** [comment]
![Снимок экрана (20)](https://github.com/Zergatul/cheatutils/assets/88514605/1cd3a675-7730-493e-9e7b-55eab09346e3)

**Comment by Zergatul** [comment]
Can you check dev console in browser and see if there are any errors?

**Comment by HitoshiMossi** [comment]
![Снимок экрана (21)](https://github.com/Zergatul/cheatutils/assets/88514605/bd95b4a2-fb4d-44f4-81d4-17c1bdf84747)
i dunno if screenshot right thing

**Comment by HitoshiMossi** [comment]
![Снимок экрана (22)](https://github.com/Zergatul/cheatutils/assets/88514605/7b84dd5c-6597-4068-b032-45dd7ce00795)
also when i click "back" button in "add block" list

**Comment by HitoshiMossi** [comment]
> Can you check dev console in browser and see if there are any errors?

![Снимок экрана (21)](https://github.com/Zergatul/cheatutils/assets/88514605/bd95b4a2-fb4d-44f4-81d4-17c1bdf84747)
i dunno if screenshot right thing

![Снимок экрана (22)](https://github.com/Zergatul/cheatutils/assets/88514605/7b84dd5c-6597-4068-b032-45dd7ce00795)
also when i click "back" button in "add block" list

**Comment by Zergatul** [comment]
What mc version and mod version is this?

**Comment by HitoshiMossi** [comment]
> What mc version and mod version is this?

1.20.1, forge, used 2.7.3 version of cheatutils mod, also i used these mods:
baritone
advancement plaques
ambient sounds
appleskin
ars nouveau
born in chaos
botania
canary mc
clumps
creative core
curios
epic fight
fastload 
fetzi's asian decoration
free cam
fuze relics
geckolib
iceberg
immersive aircraft
just enough items
JoJo: World of Stands
journey map
patchouli
plasmo voice
player animation lib
rubidium
sounds physics
starlight
weapons of miracles
wild west guns 3d

**Comment by Zergatul** [comment]
Try starting from fresh config. Remove `zergatulcheatutils.json` from `config` directory. If you are switching between different mods/modpacks with custom blocks config can get broken.

**Comment by HitoshiMossi** [comment]
> Try starting from fresh config. Remove `zergatulcheatutils.json` from `config` directory. If you are switching between different mods/modpacks with custom blocks config can get broken.
it worked, thanks!

**Comment by HitoshiMossi** [comment]
> Try starting from fresh config. Remove `zergatulcheatutils.json` from `config` directory. If you are switching between different mods/modpacks with custom blocks config can get broken.

it worked, thanks!
