### ISSUE TITLE
Shulker tooltip should display on the right if there's not enough space to the left

### ISSUE THREAD

**Issue by nayfaan** [Zergatul/cheatutils#73]
<img width="615" alt="スクリーンショット 2024-03-26 0 21 05" src="https://github.com/Zergatul/cheatutils/assets/10527873/7b4cee19-f3d1-4718-abbf-ed198fadccbe">

Left of the above image is the left edge of the screen. Currently, all tooltips are shown to the left of the item, and a lot of the times the tooltip is truncated on the left if the shulker box item is on the left side of the UI.

**Comment by Zergatul** [comment]
Fixed in 2.13.2
