### ISSUE TITLE
1.20.6?

### ISSUE THREAD

**Issue by nayfaan** [Zergatul/cheatutils#77]
Hi, I see you have a new commit for 1.20.6, but there's no new upload to curseforge? Did you forget to upload it / uploaded it somewhere else / is development still incomplete for 1.20.6?

**Comment by Zergatul** [comment]
![image](https://github.com/Zergatul/cheatutils/assets/1272144/3e1b9aa2-1cac-4159-a77a-88ecb465fe04)

For some reasons curseforge automatic system started marking cheatutils jar for manual approval. And manual approval took 5 days last time.

You can find direct download links in matrix.

**Comment by nayfaan** [comment]
Thank you
