### ISSUE TITLE
villager Rolling

### ISSUE THREAD

**Issue by Yu-Hayate** [Zergatul/cheatutils#78]
I don't know how to program in java... so I have no idea how to make a villager trading roller automatic with the provided functions,
could you help me out here?

**Comment by Yu-Hayate** [comment]
well by java i mean your scripting language [java-scripting-language](https://github.com/Zergatul/java-scripting-language)
Public

**Comment by Zergatul** [comment]
You should better join matrix, github issues is not the best place for things like this

**Comment by Yu-Hayate** [comment]
ok

**Comment by Zergatul** [comment]
BTW, did you watch tutorial video? I show examples here from very simple scripts to pretty complex.

**Comment by Yu-Hayate** [comment]
I watched them,
I'm also subscribed lol

**Comment by Zergatul** [comment]
Thanks 😊
I mean video dedicated specifically to Villager Roller. If you understand programming basics you should be able to adjust scripts I am showing here

**Comment by Yu-Hayate** [comment]
ho i didnt notice you had more vidoes lol
yeah ima take a look thx for the info!

and yeah i use javascript, html and some css sometimes c#

**Comment by Zergatul** [comment]
My scripting language is more similar to C# than to Java

**Comment by Yu-Hayate** [comment]
alright then, I better get to making lol, thx

**Comment by Yu-Hayate** [comment]
yeah no I'm very lost in this code. Xd

**Comment by Yu-Hayate** [comment]
so i have a problem with the mod.. i cant see any of the text that should be displayed like when i make this script, i dont have any visual display on my screen
![image](https://github.com/Zergatul/cheatutils/assets/112352934/7fdba746-dc05-4320-bff4-a9b70085283e)
or when im using the villagerRoller, i dont get any text displayed to my screen

**Comment by Yu-Hayate** [comment]
![image](https://github.com/Zergatul/cheatutils/assets/112352934/31c18fe4-1b9b-4e35-bdb6-a4d7f2103671)

**Comment by Zergatul** [comment]
This script is for Status Overlay module, not for Event Scripting.

**Comment by Yu-Hayate** [comment]
i still dont have any display but thats fine

**Comment by Zergatul** [comment]
Does ESP work for you? Maybe you disabled it with default key `\`

**Comment by Yu-Hayate** [comment]
yes esp works

**Comment by Yu-Hayate** [comment]
i got the villager roller to work so thats a +
