### ISSUE TITLE
loyalty enchantment villagerRoller.getMaxLevel() error 

### ISSUE THREAD

**Issue by Yu-Hayate** [Zergatul/cheatutils#80]
villagerRoller.getMaxLevel() returns 2 for the loyalty enchantment. should be 3

**Comment by Zergatul** [comment]
It is 3 for me
I don't hardcode these values. I am getting them from actual data stored in minecraft registries.

**Comment by Yu-Hayate** [comment]
damn, ig it just made an error or something idk.
¯\_(ツ)_/¯
