### ISSUE TITLE
Crash with Timeless and Classics Zero [1.20.1 Forge]

### ISSUE THREAD

**Issue by num3raI** [Zergatul/cheatutils#84]
Mod link: https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-zero
Crash report:
https://pastebin.com/VnfZcUFP

**Comment by Zergatul** [comment]
Some guy mentioned the same conflict is happening to my freecam mod. I will release fix for freecam first, and will work on cheatutils next.

**Comment by Zergatul** [comment]
Can you join matrix server to test fix for this?

**Comment by Nov1st2k10** [comment]
This is an issue for me as well.

**Comment by num3raI** [comment]
Unfortunately late reply, I've joined the matrix server.

**Comment by Zergatul** [comment]
Fixed in 2.7.6 for 1.20.1
