### ISSUE TITLE
whats an action

### ISSUE THREAD

**Issue by Djspac3** [Zergatul/cheatutils#86]
i dont have matrix and prob not gona make one soooo yea just asking bc i want to use `delayed.run()` soo i can make fake lag work well
this is what i coded
`fakeLag.enable();`
`delayed.run(math.randomInt(10,30),() => {`
`    fakeLag.disable()`
`});`
multi line bc IDK

**Comment by Zergatul** [comment]
So what's the question

**Comment by Djspac3** [comment]
How do I make that code work so that when it's activated (by keybind) fake lag turns off after a second

Also, sorry I don't check github much. I was just here because I noticed I had a notification that I was going to make an issue for a mod for geometry dash not working on android

**Comment by Zergatul** [comment]
Your code is ok, you just missed semicolon.

**Comment by Zergatul** [comment]
I see bug in `int randomInt(int min, int max)`. Use `10 + math.randomInt(20)` instead.

**Comment by Zergatul** [comment]
Also I just checked, fake lag is broke in latest 1.20.6 version

**Comment by Djspac3** [comment]
oh, odd also I'm using 1.20.4 I think it's still broken though
