### ISSUE TITLE
Esp won't automatically scan for block entities

### ISSUE THREAD

**Issue by Djspac3** [Zergatul/cheatutils#88]
block Esp is not showing blocks like chests, trapped chests, ender chests, and shulkers without first opening them (please note i don't have ANY blocks set for Esp other than that)

**Comment by Zergatul** [comment]
it can be conflict with with farsight mod
i fixed this in few cheatutils versions (not all)

**Comment by Djspac3** [comment]
I don't have a farsight mod though and I don't know any mods that are for far sight that I'm running and not even running any of the chunk visuals

**Comment by Zergatul** [comment]
Anyway, this looks like some mod conflict. Cheatuitls mod scans chunks in the background. It also processes any block update events. When you open chest, or start mining block - you get block update event from server. For some reasons block scanning is not working for you, but block events are fine.

**Comment by Djspac3** [comment]
my mods are baritone, cheatutils, cubes without borders, dynamic fps, ferritecore, immediately fast, item physics lite, lazyDFU, malilib, memory leak fix, mod menu, nbt autocomplete, nbt editor, sodium, tweakermore, and tweakeroo

**Comment by Zergatul** [comment]
I don't remember cases when these mods were causing issues, some of them I am seeing first time
If you want this fixed you need to figure out what mod is causing conflict by yourself

**Comment by Djspac3** [comment]
i could upload the log

It may take while since I am using a shared p c

**Comment by Zergatul** [comment]
log can help

**Comment by Djspac3** [comment]
K I might have to do it tomorrow, tho

**Comment by Djspac3** [comment]
I'm gonna send a repository link and then put it in there.It's gonna be private Because I am not comfortable with possibly private information getting sent out

**Comment by Zergatul** [comment]
Join matrix server, and send logs there

**Comment by Djspac3** [comment]
Oh I don't got one and for a reason I won't say I can't make one

**Comment by Djspac3** [comment]
But I sent the invite still for the repo

**Comment by Zergatul** [comment]
Ok, so you don't want to join matrix, but you expect me to share IP with you?

Owners of ... will be able to see:

    Your public profile information
    Certain activity within this repository
    Country of request origin
    Your access level for this repository
    Your IP address

**Comment by Djspac3** [comment]
oh so that just matrix? so it just lets you see that? 
its fine you don't have to send the Ip I can check it to make an account  its just im not sure about it

**Comment by Djspac3** [comment]
yea i joined `dj__`
