### ISSUE TITLE
Crash when used with a modpack

### ISSUE THREAD

**Issue by DatKorso** [Zergatul/cheatutils#89]
https://mclo.gs/5xlLcBg

I wanted to try using your mod with the Industrial Village 1.5 modpack. I have attached a link to the log above. Unfortunately, I don’t understand errors, but judging by the log the problem is in mixins. I would be grateful if you could help me find out which mod is causing this error.

**Comment by Zergatul** [comment]
Looks like conflict with controllable mod. If you don't play with controller you don't need it.

**Comment by DatKorso** [comment]
> Looks like conflict with controllable mod. If you don't play with controller you don't need it.

Omg it works! Thank you so much!
