### ISSUE TITLE
Scripting API Request: Movement speed multiplier method for Status Overlay that returns current multiplier

### ISSUE THREAD

**Issue by GoliathX211** [Zergatul/cheatutils#9]
I noticed there is movement.isSpeedMultiplierEnabled() and movement.toggleSpeedMultiplier() for scripts but there are no such methods in Status Overlay to obtain the multiplier in a String format. The method isSpeedMultiplierEnabled also is not on Status Overlay.

**Comment by Zergatul** [comment]
There is no specific reason for this. I can add as many functions to APIs as we want. I didn't add them because I didn't need them initially.
