### ISSUE TITLE
Neoforge issue 

### ISSUE THREAD

**Issue by DatKorso** [Zergatul/cheatutils#92]
![image](https://github.com/Zergatul/cheatutils/assets/91170456/8f3ae44f-350d-4ffc-9bbb-8df0147bd98b)

Any plans for an update for Neoforge?

Used on modpack ATM10

**Comment by Zergatul** [comment]
The only thing I can dream of is another mod loader 💀

![image](https://github.com/Zergatul/cheatutils/assets/1272144/6f4964ba-27c7-4808-8e7f-60a84360a871)

**Comment by DatKorso** [comment]
> The only thing I can dream of is another mod loader 💀
> 
> ![image](https://private-user-images.githubusercontent.com/1272144/345477623-6f4964ba-27c7-4808-8e7f-60a84360a871.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTk1OTcsIm5iZiI6MTcyMDAxOTI5NywicGF0aCI6Ii8xMjcyMTQ0LzM0NTQ3NzYyMy02ZjQ5NjRiYS0yN2M3LTQ4MDgtOGU3Zi02MGE4NDM2MGE4NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTUwODE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU4Y2U0YjY1NmJiNmUyMDllZTA3NmY4MmE0YjA5YjIwNzk2OWI0NmRmYzY2N2IzOWVmZGZiNjAxZGM2NmFhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nEdQVdSXeKMYR3e1ZngNTmRe7WmQp3uk6gcgV0DtYOI)

Ahahaha, ok, no problem!

**Comment by Zergatul** [comment]
If a lot of guys want NeoForge I may think of adding it. But currently it doesn't look like NeoForge has at least 10% of mod loader share.
You may leave this issue open, if other guys will have decent arguments to add NeoForge they may add information here.

**Comment by luffykick** [comment]
I  pray we could have neoforge support also.

**Comment by Zergatul** [comment]
Added neoforge for 1.21

**Comment by morris-nn** [comment]
> Добавлен neoforge для версии 1.21

Will the mod be for versions lower than 1.21 neoforge?

**Comment by Zergatul** [comment]
> > Добавлен neoforge для версии 1.21
> 
> Will the mod be for versions lower than 1.21 neoforge?

no. someone in curseforge comments said 1.20.x forge version can work with neoforge
