### ISSUE TITLE
No available version on Prism Launcher

### ISSUE THREAD

**Issue by UnLegitCombos** [Zergatul/cheatutils#93]
When I try to update or download this mod directly from Prism Launcher it can't find any available version so it resorts to suggesting to download it manually.
![image](https://github.com/Zergatul/cheatutils/assets/51376300/89f5876e-79d2-4d46-a68e-6a1a0a54fc17)
![image](https://github.com/Zergatul/cheatutils/assets/51376300/7e46e13d-176a-40a6-b54e-4f9301537173)

**Comment by Zergatul** [comment]
I have no idea why this happen and how it should work. I didn't change any settings lately

**Comment by UnLegitCombos** [comment]
Found this on their discord server

![image](https://github.com/Zergatul/cheatutils/assets/51376300/49ca8e5a-4baf-425f-83b9-3006121f9f12)
https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

**Comment by Zergatul** [comment]
If you enable this, it says:
Be aware that downloads outside CurseForge ecosystem do not count towards the rewards program. 
💀💀💀
I don't try to make any money, but I think there are a lot of mod creators who do
I enabled this for cheatutils

**Comment by UnLegitCombos** [comment]
Yeah, I didn't even know that was a thing, but usually most people don't use 3rd party apps and this being the first mod that I have seen with this issue, I assume that its not that big of a hit to revenue.

Anyways, thank you very much, saves me and some other people a bunch of time not having to redownload manually after every update.
I do suggest giving prism a try, its extremely convenient.
